  - hosts: localhost
    connection: local
    roles:
      - { role: iroha-config-gen }

  # - hosts: all
  #   gather_facts: False
  #   pre_tasks:
  #   - name: install python 2  # python installation (ansible hosts gather_facts requirement)
  #     raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
  #     changed_when: False
  #     become: yes
  #   roles:
  #     - { role: docker, tags: docker }
  #     - { role: iroha-nodes }
